#practice 2
student_marks=[]
s1=input("Enter the first student marks:")
student_marks.append(s1)
print(student_marks)
s2=input("Enter the first student marks:")
student_marks.append(s2)
print(student_marks)
s3=input("Enter the first student marks:")
student_marks.append(s3)
print(student_marks)
s4=input("Enter the first student marks:")
student_marks.append(s4)
print(student_marks)
s5=input("Enter the first student marks:")
student_marks.append(s5)
print(student_marks)
s6=input("Enter the first student marks:")
student_marks.append(s6)
print("student marks : ",student_marks)
student_marks.sort()
print("sorted student marks : ",student_marks)
