
s=set()
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
numbers=input("Enter the number:")
s.add(numbers)
print(s)

